import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/src/components/Navbar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Me Caso - Mi proyecto",
  description: "Generated by yo mismo",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="es" // Cambiamos el idioma base a español
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-white">
        
        {/* 2. Colocamos el Navbar justo al inicio del Body */}
        <Navbar />

        {/* 3. Envolvemos a las páginas hijas (children) para que ocupen el resto del espacio */}
        <main className="flex-1 flex flex-col">
          {children}
        </main>
        
      </body>
    </html>
  );
}